# Generated by Django 5.0.6 on 2024-07-09 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Presente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('presente', models.TextField(max_length=255)),
                ('valor', models.FloatField()),
                ('descricao', models.TextField(max_length=350)),
                ('link_img', models.TextField(max_length=255)),
                ('quantidades', models.IntegerField()),
            ],
        ),
    ]
