# Generated by Django 5.0.6 on 2024-07-10 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presente',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='presente',
            name='link_img',
        ),
        migrations.RemoveField(
            model_name='presente',
            name='quantidades',
        ),
    ]
