# Generated by Django 5.0.6 on 2024-07-10 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_presente_descricao_remove_presente_link_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='presente',
            name='descricao',
            field=models.TextField(default='', max_length=350),
        ),
        migrations.AddField(
            model_name='presente',
            name='link_img',
            field=models.TextField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='presente',
            name='quantidades',
            field=models.IntegerField(default=0),
        ),
    ]
