# Generated by Django 5.0.6 on 2024-08-21 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_presente_descricao_presente_link_img_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Convidado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField(max_length=255)),
                ('acompanhantes', models.IntegerField()),
                ('codigo', models.IntegerField()),
            ],
        ),
    ]
