# Generated by Django 5.0.6 on 2024-08-27 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_convidado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='convidado',
            options={'ordering': ['acompanhantes']},
        ),
    ]
