# Generated by Django 5.0.6 on 2024-08-30 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_convidado_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convidado',
            name='codigo',
            field=models.TextField(default='aberto', max_length=25),
        ),
    ]
