# Generated by Django 5.0.6 on 2024-08-30 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_convidado_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='convidado',
            name='confirmaçao',
            field=models.TextField(default='aberto', max_length=25),
        ),
        migrations.AlterField(
            model_name='convidado',
            name='codigo',
            field=models.IntegerField(),
        ),
    ]
