# Generated by Django 5.0.6 on 2024-08-30 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_convidado_confirmaçao_alter_convidado_codigo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Convidados_confirmados',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('db_convidados', models.TextField(max_length=255)),
            ],
        ),
    ]
