# Generated by Django 5.0.6 on 2024-09-02 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_convidados_confirmados'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presentes_ganho',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField(max_length=255)),
                ('codigo', models.IntegerField()),
            ],
        ),
    ]
