# Generated by Django 5.0.6 on 2024-09-02 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_presentes_ganho_id_presente'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentes_ganho',
            name='nome_presente',
            field=models.TextField(default='', max_length=255),
        ),
    ]
