# Generated by Django 5.0.6 on 2024-09-04 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_presentes_ganho_nome_presente'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='convidado',
            options={'ordering': ['nome']},
        ),
    ]
