# Generated by Django 5.0.6 on 2024-09-04 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_convidado_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='presente',
            options={'ordering': ['quantidades']},
        ),
    ]
